# language: node_js
# node_js:
# - '8'

addons:
  ssh_known_hosts:
  - wangdoc.com

# sudo: required

before_install:
- openssl aes-256-cbc -K $encrypted_54e6d4f451da_key -iv $encrypted_54e6d4f451da_iv
  -in wangdoc-deploy-rsa.enc -out wangdoc-deploy-rsa -d
# - echo -e "Host wangdoc.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
# - echo -e "Host wangdoc.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - echo -e "Host $host_ip\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: bash ./deploy.sh
